[0m21:13:00.811081 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2d6421ded0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2d62cb6050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2d62cb60e0>]}


============================== 21:13:00.818776 | 4ef31a1f-6e97-47a5-a8c5-e04f70ab6dd1 ==============================
[0m21:13:00.818776 [info ] [MainThread]: Running with dbt=1.5.0
[0m21:13:00.819589 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '.', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m21:13:00.820333 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-vivien/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m21:13:00.821169 [debug] [MainThread]: Command `dbt deps` failed at 21:13:00.820996 after 0.01 seconds
[0m21:13:00.821712 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2d6421ded0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2d62cb5ea0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2d62cb5d80>]}
[0m21:13:00.823038 [debug] [MainThread]: Flushing usage events
[0m21:16:44.548034 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f14ce57dea0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f14cd09a020>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f14cd09a0b0>]}


============================== 21:16:44.551651 | bd7bb175-56fb-4af4-93b2-6c78a1362b57 ==============================
[0m21:16:44.551651 [info ] [MainThread]: Running with dbt=1.5.0
[0m21:16:44.552497 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': '/home/vscode/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m21:17:49.570185 [debug] [MainThread]: Starter project path: /home/vscode/.local/lib/python3.10/site-packages/dbt/include/starter_project
[0m21:19:25.420502 [info ] [MainThread]: Profile coffee_shop_vvnlo written to /home/vscode/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m21:19:25.421310 [info ] [MainThread]: 
Your new dbt project "coffee_shop_vvnlo" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m21:19:25.422560 [debug] [MainThread]: Command `dbt init` succeeded at 21:19:25.422188 after 160.88 seconds
[0m21:19:25.423052 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f14ce57dea0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f14cb5a5840>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f14cb5a58d0>]}
[0m21:19:25.423505 [debug] [MainThread]: Flushing usage events
[0m05:53:08.078785 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8ed76b1ea0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8ed61967d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8ed6196650>]}


============================== 05:53:08.083220 | 3aa67cce-cbc9-4684-8c0e-555bae183fe7 ==============================
[0m05:53:08.083220 [info ] [MainThread]: Running with dbt=1.5.1
[0m05:53:08.084084 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/vscode/.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m05:53:08.084724 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-vivien/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m05:53:08.085584 [debug] [MainThread]: Command `dbt run` failed at 05:53:08.085416 after 0.02 seconds
[0m05:53:08.086117 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8ed76b1ea0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8ed6196740>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8ed61969b0>]}
[0m05:53:08.086718 [debug] [MainThread]: Flushing usage events
[0m10:16:58.502694 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f4f78acfc10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f4f76c27d30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f4f76c27d00>]}


============================== 10:16:58.506497 | a3695a3c-7e53-4364-aec1-8e166b6002f7 ==============================
[0m10:16:58.506497 [info ] [MainThread]: Running with dbt=1.6.0
[0m10:16:58.507459 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': '/home/vscode/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m10:16:58.508052 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-vivien/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m10:16:58.509118 [debug] [MainThread]: Command `dbt run` failed at 10:16:58.508949 after 0.02 seconds
[0m10:16:58.509643 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f4f78acfc10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f4f76c27d00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f4f76c27e80>]}
[0m10:16:58.510091 [debug] [MainThread]: Flushing usage events
[0m09:09:56.683601 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe19f933be0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe19dc91180>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe19dc910f0>]}


============================== 09:09:56.691189 | 74797c54-892a-4ba1-909b-5f727e026843 ==============================
[0m09:09:56.691189 [info ] [MainThread]: Running with dbt=1.6.6
[0m09:09:56.691910 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/vscode/.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt run', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m09:09:56.692430 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-vivien/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m09:09:56.693123 [debug] [MainThread]: Command `dbt run` failed at 09:09:56.693017 after 0.02 seconds
[0m09:09:56.693510 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe19f933be0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe19dc91090>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe19dc91960>]}
[0m09:09:56.693932 [debug] [MainThread]: Flushing usage events
